name: Daily Stock Data Update

on:
  schedule:
    - cron: '30 1 * * 1-5'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install yfinance

    - name: Run Update Script
      run: python update_table.py

    - name: Commit and Push if index.html changed
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git fetch origin main
        git pull origin main --rebase
        git add index.html
        git diff --quiet && git diff --staged --quiet || (git commit -m "📊 Auto-Update: Latest Market Close Data" && git push origin main)
